settings:
  title: 'Status Page'
  url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: www.google.de
    name: www.google.de
    description: 'Built for anything connected to the Internet.'
    url: 'https://www.google.de'
    method: GET
    expectStatus: 200
    linkable: false # allows the title to be a link, default=true
    
  - id: letnet.cc
    name: letnet.cc
    description: 'Dashboard providing Links to all my services'
    url: 'https://letnet.cc/'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true
    
  - id: dashboard.letnet.cc
    name: dashboard.letnet.cc
    description: 'Dashboard providing Links to all my services'
    url: 'https://dashboard.letnet.cc/'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true
    
  - id: vaultwarden.letnet.cc
    name: vaultwarden.letnet.cc
    description: 'Selfhosted Password Manager'
    url: 'https://vaultwarden.letnet.cc/'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true
    
  - id: search.letnet.cc
    name: search.letnet.cc
    description: 'Selfhosted privacy-focused searchengine to use instead of Google'
    url: 'https://search.letnet.cc/'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true
